### PR TITLE
Fix reading VBS backup description

### LINKED ISSUE #100: [VBS] description in get response is broken
When getting 
`backupDetails, err := backups.Get(client, backupID).Extract()`
Description in the response differs with the description in create options:
`"{\"DESC\": \"Backup_Demo\", \"INC\": 1}"` instead of `"Backup_Demo"`

Found in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/843

### PR DESCRIPTION
**Pull request by outcatcher**
### What this PR does / why we need it
Read exact description instead of strange JSON

Add VBS v2 backup acceptance test

Add `NewVBSServiceV2` function

Move volume creation/deletion to acceptance test `common` library

### Which issue this PR fixes
Fix #100

### CODE REVIEW

File: acceptance/openstack/vbs/v2/backups_test.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+		t.Log("backup successfully deleted")
+	}()
+
+	backupDetails, err := backups.Get(client, backupID).Extract()
+	th.AssertNoErr(t, err)
+	th.AssertEquals(t, opts.Description, backupDetails.Description)
+	th.AssertEquals(t, opts.Name, backupDetails.Name)
+}
+
+func deleteSnapshot(client *golangsdk.ServiceClient, id string) error {
```
Comment (lego963) [inline acceptance/openstack/vbs/v2/backups_test.go]: what about to create `helpers.go` and move `deleteShnapshot` with `deleteVolumeSnapshots` there?

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

File: acceptance/openstack/vbs/v2/backups_test.go (hunk 1 above)
Comment (outcatcher) [reply acceptance/openstack/vbs/v2/backups_test.go]: Snapshot deleting is used only in backup test now, let's keep it here for now

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by outcatcher** [comment]
regate

**Comment by outcatcher** [comment]
regate
