### PR TITLE
[CTS] Fix issue with required `operations` field

### LINKED ISSUE #213: [CTS] Remove requiring json option in `operations`
Required for: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/556

### PR DESCRIPTION
**Pull request by lego963**
### What this PR does / why we need it
Fix issue with required `operations` field in `cts/v1/trackers` pkg

### Which issue this PR fixes
Fixes: #213 

### Special notes for your reviewer

```
=== RUN   TestTrackersLifecycle
    helpers.go:15: Attempting to create OBS bucket
    helpers.go:28: Created OBS Bucket: obs-cts-test4eass
    helpers.go:44: Attempting to create SMNv2 topic
    helpers.go:57: Created SMNv2 Topic: urn:smn:eu-de:5045c215010c440d91b2f7dce1f3753b:smn-cts-testcqx2o
    trackers_test.go:21: Attempting to create CTSv1 Tracker
    trackers_test.go:38: Created CTSv1 Tracker: system
    trackers_test.go:43: Attempting to update CTSv1 Tracker: system
    trackers_test.go:50: Updated CTSv1 Tracker: system
    trackers_test.go:32: Attempting to delete CTSv1 Tracker: system
    trackers_test.go:35: Deleted CTSv1 Tracker: system
    helpers.go:62: Attempting to delete SMNv2 topic: urn:smn:eu-de:5045c215010c440d91b2f7dce1f3753b:smn-cts-testcqx2o
    helpers.go:67: Deleted SMNv2 Topic: urn:smn:eu-de:5045c215010c440d91b2f7dce1f3753b:smn-cts-testcqx2o
    helpers.go:34: Attempting to delete OBS bucket: obs-cts-test4eass
    helpers.go:40: Deleted OBS Bucket: obs-cts-test4eass
--- PASS: TestTrackersLifecycle (11.98s)
PASS

Process finished with the exit code 0
```

### CODE REVIEW

File: openstack/cts/v1/tracker/requests.go [hunk 1]
```diff
@@ -96,10 +96,10 @@ type CreateOpts struct {
 }
 
 type SimpleMessageNotification struct {
-	IsSupportSMN          bool     `json:"is_support_smn"`
-	TopicID               string   `json:"topic_id"`
-	Operations            []string `json:"operations" required:"true"`
-	IsSendAllKeyOperation bool     `json:"is_send_all_key_operation"`
+	IsSupportSMN          *bool    `json:"is_support_smn" required:"true"`
```
Comment (outcatcher) [inline openstack/cts/v1/tracker/requests.go]: Why using bool pointer for the required field?

**Review by outcatcher — CHANGES_REQUESTED** [review]

**Review by outcatcher — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by outcatcher — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — APPROVED** [review]
